---
title: "System Modeling"
format: 
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: true
    code-tools: true
jupyter: python3
---

## Slide 2 - Motivation and Learning Outcomes

### Developing a models is step *ZERO*

- Over the years several modeling techniques have been developed.
- We want to explore their roots
- Different methods have better (or worse) applications
- In the Aero/Mechanical world we are generally concerned with:
  - Dynamics/Mechanics
  - Vibrations
  - ??

## Slide 3 - The Heritage of Mechanics

Free body diagrams and Newton's description of motion. The Principia: mathematical principles of natural philosophy

$$\vec{F} = m \vec{a} = \frac{d}{dt} (m \vec{v})$$

For the MSD system,

$$m \ddot{q} + c \dot{q} + k q = f(t)$$

## Slide 4 - State, Time, and Space

We plot the response of the MSD system explicitly in time.

We can also plot the response in state space, where we plot the position and velocity of the system as a function of time. This allows us to visualize the dynamics of the system in a different way.

We can represent a system of higher order differential equations as a system of first order differential equations. This is the basis of the state space representation of a system.

This approach lends itself to numerical solving methods like Runge-+Kutta and the tools of vector spaces and Real/Comples analysis.

::: callout-note
Do IC plot and Phase Plane Matlab example for the MSD system.
:::

- State Space gives a sense of flow and the vector field of the system for any initial conditions.
- State Space gives a sense of the stability of the system, and how it will respond to perturbations.

## Slide 5 - The Heritage of Electrical Engineering

Fundational to this approach is the idea of input and output of a system. Systems can be reduced to subsystems, etc., and analyzed as a whole. This is the basis of the block diagram approach to modeling systems.

## Slide 6 - Step and Frequency Response

We've talked about the step response from a performance perspective, but we can also look at the step response from a modeling perspective. The step response is a fundamental tool for understanding the dynamics of a system.

The frequency response is another fundamental tool for understanding the dynamics of a system. The frequency response tells us how the system responds to different frequencies of input, and can be used to analyze the stability and performance of the system.

Mostly we want to understand how the magnitude and phase of the output changes with frequency. This is the basis of Bode plots, which are a fundamental tool for analyzing the frequency response of a system.

::: callout-note
Do step response and Bode plot Matlab example for the MSD system.
:::

## Slide 7 - The Control View - State Space

$$ \frac{dx}{dt} = f(x, u), \ y = h(x, u) $$

$x$ is the *state* vector $u$ is the *input* vector $y$ is the *output* vector

$f$ is the *state function* $h$ is the *output function*

These functions describe how the state of the system evolves over time, and how the output of the system is related to the state and input.

With these functions and these views, it is natural to ask questions like:

- Does the state converge? (Stability)

- What states can the system reach given the proper choice of u(t)? (controllability or reachability)

- If we don’t measure the whole state, can we reconstruct the state? (observability)

- Notice the answers to these questions should not depend on the system we are working with, but on properties of the model

## Slide 8 - Summary